version: "3.9"
services:
  flask-backend:
    build:  ./API
    ports:
    - "81:5000"
    volumes:
    - ./API:/app
    environment:
      FLASK_ENV: development
    command: python3 api.py
  web:
    build: ./my-app
    ports:
      - "3000:3000"
    volumes:
      - ./my-app:/user/src/app
    depends_on:
      - flask-backend
    command: npm start
